import React from 'react';
import Head from 'next/head'
import dynamic from 'next/dynamic'
import styles from '@@/styles/Room.module.css'
import { v4 as uuidv4 } from "uuid";

const ChatRoom = dynamic(() => import('@@/components/ChatRoom'), { 
  ssr: false,
})

const Home = () => {
  const userId = uuidv4();

  return (
    <>
      <Head>
        <title>Vid chat app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.header}>
          <h3>Video Chat</h3>
      </div>
      <div className={styles.main}>
        <ChatRoom />
      </div>
    </>
  )
}

export default Home
